<?php

namespace Database\Seeders;

use App\Enums\ContentStatus;
use App\Enums\ProjectStatus;
use App\Models\Document;
use App\Models\DocumentCategory;
use App\Models\NewsArticle;
use App\Models\NewsCategory;
use App\Models\Programme;
use App\Models\Project;
use App\Support\DemoImageGenerator;
use App\Support\DemoPdfGenerator;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Populates every content table with realistic, clearly-marked placeholder
 * content so the homepage (and the admin panel) look credible for a client
 * review before real Department content lands.
 *
 * Every record this seeder creates carries `is_demo = true` and is removed,
 * media included, by `php artisan demo:purge`.
 *
 * Imagery is generated at seed time by DemoImageGenerator (palette gradients
 * from GD, labelled "DEMO — <subject>") rather than sourced photography —
 * see docs/superpowers/specs/2026-08-07-foundation-homepage-design.md §6 for
 * why. Document files are generated by DemoPdfGenerator for the same reason:
 * zero licensing risk, the seeder runs fully offline, and a placeholder that
 * survives into production is obvious on sight.
 */
class DemoContentSeeder extends Seeder
{
    public function run(): void
    {
        $programmes = $this->seedProgrammes();
        $this->seedNewsArticles();
        $this->seedProjects($programmes);
        $this->seedDocuments();
    }

    /** @return array<string, Programme> keyed by title, for linking projects. */
    private function seedProgrammes(): array
    {
        $programmes = [
            [
                'title' => 'Conservation Programme',
                'summary' => 'Protecting Niue\'s native forests, coastal habitats and the species that depend on them.',
                'body' => "Niue's terrestrial and coastal ecosystems support species found nowhere else. This programme coordinates habitat protection, invasive species control and long-term ecological monitoring across the island, working alongside village councils and landowners who hold customary responsibility for much of Niue's land.\n\nActivities include boundary surveys of protected areas, community-led replanting of native forest, and monitoring of coastal vegetation that stabilises the island's limestone coastline against erosion.",
                'palette' => 'forest',
                'subject' => 'conservation',
                'featured' => true,
            ],
            [
                'title' => 'Waste Management Programme',
                'summary' => 'Reducing landfill dependence through recycling, composting and safer disposal of hazardous waste.',
                'body' => "Niue's small land area makes sustainable waste management essential. This programme covers household and commercial waste collection, a recycling stream for common materials, a community composting initiative, and safe handling procedures for hazardous items such as batteries and used oil.\n\nThe Department works with other government agencies and village councils to keep collection routes reliable and to expand what can be diverted from landfill each year.",
                'palette' => 'waste',
                'subject' => 'waste management',
                'featured' => false,
            ],
            [
                'title' => 'Marine Conservation Programme',
                'summary' => 'Safeguarding Niue\'s reefs, deep-water habitats and the island\'s marine protected area.',
                'body' => "Niue's surrounding waters hold coral reef systems and deep-water habitats of significant ecological value. This programme supports reef health monitoring, sustainable fisheries practices, and community stewardship of marine protected areas.\n\nWork includes coordinating with local dive operators and fishers on responsible-use guidelines, and supporting monitoring of reef condition over time so management decisions are based on current data rather than assumption.",
                'palette' => 'marine',
                'subject' => 'marine conservation',
                'featured' => true,
            ],
            [
                'title' => 'Biodiversity Programme',
                'summary' => 'Documenting and protecting the native flora and fauna that make up Niue\'s biodiversity.',
                'body' => "Understanding what species are present, and where, is the foundation of effective conservation. This programme runs biodiversity surveys across forest, coastal and marine habitats, maintains records of native and endemic species, and supports control of invasive species that threaten them.\n\nFindings feed directly into the Conservation and Marine Conservation programmes, so protection effort is directed where it is most needed.",
                'palette' => 'forest',
                'subject' => 'biodiversity',
                'featured' => true,
            ],
            [
                'title' => 'Climate Resilience Programme',
                'summary' => 'Helping Niue communities and infrastructure adapt to a changing climate.',
                'body' => "As a small island nation, Niue faces particular exposure to climate-related risks including cyclones, coastal erosion and changing rainfall patterns. This programme supports climate adaptation planning, community resilience initiatives, and coordination with regional climate bodies.\n\nWork includes supporting village-level resilience planning and contributing environmental data to national climate adaptation strategy.",
                'palette' => 'climate',
                'subject' => 'climate resilience',
                'featured' => false,
            ],
            [
                'title' => 'Community Clean-Up Programme',
                'summary' => 'Coordinating village and school clean-up initiatives across Niue.',
                'body' => "Community participation is central to keeping Niue's villages, coastline and public spaces free of litter and illegal dumping. This programme coordinates clean-up days with villages, schools and community groups, and provides equipment and guidance for safe waste handling during events.\n\nRegular clean-up activity also feeds back into the Waste Management Programme by identifying recurring dumping sites that need a longer-term solution.",
                'palette' => 'waste',
                'subject' => 'community clean-up',
                'featured' => false,
            ],
        ];

        $created = [];
        $daysAgo = 30;

        foreach ($programmes as $index => $data) {
            $programme = Programme::create([
                'title' => $data['title'],
                'slug' => Str::slug($data['title']),
                'summary' => $data['summary'],
                'body' => $data['body'],
                'is_featured' => $data['featured'],
                'sort_order' => $index,
                'status' => ContentStatus::Published,
                'published_at' => now()->subDays($daysAgo - $index),
                'is_demo' => true,
            ]);

            $this->attachFeaturedImage($programme, $data['palette'], $data['subject']);

            $created[$data['title']] = $programme;
        }

        return $created;
    }

    private function seedNewsArticles(): void
    {
        $categories = collect(['Announcements', 'Community', 'Environment Updates', 'Media Releases'])
            ->mapWithKeys(fn (string $name) => [
                $name => NewsCategory::firstOrCreate(
                    ['slug' => Str::slug($name)],
                    ['name' => $name, 'sort_order' => 0],
                ),
            ]);

        $articles = [
            [
                'title' => 'Village clean-up day draws strong community turnout',
                'excerpt' => 'Residents joined a coordinated clean-up across coastal tracks and village centres over the weekend.',
                'category' => 'Community',
                'palette' => 'waste',
                'subject' => 'community clean-up',
                'featured' => true,
            ],
            [
                'title' => 'Reef health monitoring season begins',
                'excerpt' => 'Annual monitoring of reef condition around Niue starts this month, supporting the Marine Conservation Programme.',
                'category' => 'Environment Updates',
                'palette' => 'marine',
                'subject' => 'reef monitoring',
                'featured' => true,
            ],
            [
                'title' => 'Department releases updated waste collection schedule',
                'excerpt' => 'A revised household collection schedule takes effect next month, with an expanded recycling stream.',
                'category' => 'Announcements',
                'palette' => 'waste',
                'subject' => 'waste collection',
                'featured' => false,
            ],
            [
                'title' => 'Native forest replanting continues in inland villages',
                'excerpt' => 'Community-led replanting under the Conservation Programme has added new seedlings to protected forest areas.',
                'category' => 'Environment Updates',
                'palette' => 'forest',
                'subject' => 'forest replanting',
                'featured' => false,
            ],
            [
                'title' => 'Department joins regional climate resilience workshop',
                'excerpt' => 'Staff attended a regional workshop on climate adaptation planning for small island states.',
                'category' => 'Media Releases',
                'palette' => 'climate',
                'subject' => 'climate resilience',
                'featured' => false,
            ],
        ];

        foreach ($articles as $index => $data) {
            $article = NewsArticle::create([
                'title' => $data['title'],
                'slug' => Str::slug($data['title']),
                'excerpt' => $data['excerpt'],
                'body' => "{$data['excerpt']}\n\nThis article is placeholder demo content for the Niue Department of Environment website and does not describe a real event.",
                'news_category_id' => $categories[$data['category']]->id,
                'author_name' => 'Department of Environment',
                'is_featured' => $data['featured'],
                'status' => ContentStatus::Published,
                'published_at' => now()->subDays(20 - $index * 2),
                'share_to_facebook' => false,
                'is_demo' => true,
            ]);

            $this->attachFeaturedImage($article, $data['palette'], $data['subject']);
        }
    }

    /** @param  array<string, Programme>  $programmes */
    private function seedProjects(array $programmes): void
    {
        $projects = [
            [
                'title' => 'Coastal Vegetation Restoration',
                'summary' => 'Restoring coastal vegetation to reduce erosion along vulnerable shoreline sections.',
                'programme' => 'Conservation Programme',
                'status' => ProjectStatus::Active,
                'palette' => 'forest',
                'subject' => 'coastal restoration',
                'featured' => true,
            ],
            [
                'title' => 'Village Recycling Hub Pilot',
                'summary' => 'Piloting a village-level recycling drop-off point ahead of a wider rollout.',
                'programme' => 'Waste Management Programme',
                'status' => ProjectStatus::Active,
                'palette' => 'waste',
                'subject' => 'recycling',
                'featured' => true,
            ],
            [
                'title' => 'Reef Survey and Mapping',
                'summary' => 'Mapping reef condition around Niue to establish a baseline for long-term monitoring.',
                'programme' => 'Marine Conservation Programme',
                'status' => ProjectStatus::Active,
                'palette' => 'marine',
                'subject' => 'reef survey',
                'featured' => false,
            ],
            [
                'title' => 'Coastal Resilience Planning Workshop Series',
                'summary' => 'A series of village-level workshops supporting local climate adaptation planning.',
                'programme' => 'Climate Resilience Programme',
                'status' => ProjectStatus::Planned,
                'palette' => 'climate',
                'subject' => 'climate planning',
                'featured' => false,
            ],
        ];

        foreach ($projects as $index => $data) {
            $project = Project::create([
                'title' => $data['title'],
                'slug' => Str::slug($data['title']),
                'summary' => $data['summary'],
                'body' => "{$data['summary']}\n\nThis project record is placeholder demo content for the Niue Department of Environment website.",
                'programme_id' => $programmes[$data['programme']]->id,
                'project_status' => $data['status'],
                'is_featured' => $data['featured'],
                'status' => ContentStatus::Published,
                'published_at' => now()->subDays(25 - $index * 3),
                'is_demo' => true,
            ]);

            $this->attachFeaturedImage($project, $data['palette'], $data['subject']);
        }
    }

    private function seedDocuments(): void
    {
        $categories = DocumentCategory::pluck('id', 'name');

        $documents = [
            [
                'title' => 'Annual Environment Report (Demo)',
                'description' => 'A summary of Department programme activity for the year, presented as a placeholder for the real annual report.',
                'category' => 'Reports',
                'featured' => true,
                'body' => ['Contents: programme summaries, project updates, environmental indicators.'],
            ],
            [
                'title' => 'Waste Management Policy (Demo)',
                'description' => 'Placeholder policy document outlining household and commercial waste handling.',
                'category' => 'Policies',
                'featured' => true,
                'body' => ['Contents: collection schedules, recycling guidance, hazardous waste handling.'],
            ],
            [
                'title' => 'Marine Protected Areas Legislation Summary (Demo)',
                'description' => 'Placeholder summary of legislation governing Niue\'s marine protected areas.',
                'category' => 'Legislation',
                'featured' => true,
                'body' => ['Contents: an overview of marine protected area provisions.'],
            ],
            [
                'title' => 'Environmental Impact Notification Form (Demo)',
                'description' => 'Placeholder form for notifying the Department of a proposed activity with environmental impact.',
                'category' => 'Forms',
                'featured' => false,
                'body' => ['Contents: applicant details, activity description, site location.'],
            ],
            [
                'title' => 'Biodiversity Survey Publication (Demo)',
                'description' => 'Placeholder publication summarising a biodiversity survey.',
                'category' => 'Publications',
                'featured' => false,
                'body' => ['Contents: survey methodology, species recorded, recommendations.'],
            ],
            [
                'title' => 'Community Clean-Up Guidance (Demo)',
                'description' => 'Placeholder downloadable guidance for organising a village clean-up day.',
                'category' => 'Downloads',
                'featured' => false,
                'body' => ['Contents: safety guidance, equipment checklist, waste sorting guide.'],
            ],
        ];

        foreach ($documents as $index => $data) {
            $document = Document::create([
                'title' => $data['title'],
                'slug' => Str::slug($data['title']),
                'description' => $data['description'],
                'document_category_id' => $categories[$data['category']] ?? null,
                'published_date' => now()->subDays(15 - $index)->toDateString(),
                'is_featured' => $data['featured'],
                'status' => ContentStatus::Published,
                'published_at' => now()->subDays(15 - $index),
                'is_demo' => true,
            ]);

            $pdfPath = DemoPdfGenerator::make($data['title'], $data['category'], $data['body']);

            $document->addMedia($pdfPath)
                ->preservingOriginal()
                ->toMediaCollection('file');
        }
    }

    private function attachFeaturedImage(Programme|Project|NewsArticle $model, string $palette, string $subject): void
    {
        $imagePath = DemoImageGenerator::make($palette, "DEMO — {$subject}", 1920, 900);

        $model->addMedia($imagePath)
            ->preservingOriginal()
            ->withCustomProperties(['alt' => "Placeholder image representing {$subject} (demo content)"])
            ->toMediaCollection('featured_image');
    }
}
